config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  devise_for :users

  resources :hats do
    resources :bookings, only: %i[new create edit update destroy]
  end
  resources :bookings, only: %i[index show] do
    resources :reviews, only: [:new, :create]
  end
  # Potential custom routes:
  # get 'my_listings', to: 'users#listings'
  # get 'my_bookings', to: 'users#bookings'

  # Defines the root path route ("/")
#   # root "articles#index"

# resources :hats
# resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hat
  has_many :reviews
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/hat.rb
class Hat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews
  has_one_attached :photo

  validates :color, :style, :description, presence: true
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than_or_equal_to: 1 }

  before_destroy :destroy_related_bookings

  def self.random_card_class
    (([''] * 3) + ['wide', 'tall', 'big']).sample # this ensures the normal class '' appears n times more frequently than the other sizes
  end

  private

  def destroy_related_bookings
    user.bookings.where(hat_id: id).destroy_all
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :hat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :hats, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update]
  before_action :set_hat, only: [:new, :create]
  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.hat = @hat
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def index
    @user = current_user
    @bookings = @user.bookings
  end

  def edit
    @booking = Booking.find(params[:id])
    @hat = @booking.hat
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private

  def booking_params
    params.require(:booking).permit(:hat_id, :user_id, :start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
  def set_hat
    @hat = Hat.find(params[:hat_id])
  end
end

app/controllers/hats_controller.rb
class HatsController < ApplicationController
  # index, show, create, new, edit, update
  before_action :set_hat, only: %i[show edit update destroy]

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @hats = @user.hats
    else
      @hats = Hat.all
    end
  end

  def show
  end

  def new
    @hat = Hat.new
  end

  def create
    @hat = Hat.new(hat_params)
    @hat.user = current_user
    if @hat.save
      redirect_to hat_path(@hat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @hat= Hat.find(params[:id])
    if @hat.update(hat_params)
      redirect_to hat_path(@hat), notice: 'Hat has been updated!'
    else
      render :edit
    end
  end

  def destroy
    @hat.destroy
    redirect_to hats_path, status: :see_other
  end

  private

  def set_hat
    @hat = Hat.find(params[:id])
  end

  def hat_params
    params.require(:hat).permit(:style, :color, :price, :description, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: [:new, :create, :update]

  def new
    @review = Review.new
  end

  def create
    @hat = @booking.hat
    @review = Review.new(review_params)
    @review.booking = @booking
    @review.hat = @hat
    @review.save
    redirect_to hat_path(@hat), notice: 'Review was successfully created'
end

def show
  @review = Review.find(params[:id])
end

  private
  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@hat, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <div class="btn btn-primary p-0 gnome-btn mt-4">
    <%= f.submit "Confirm booking", class: "btn btn-primary"  %>
    <img class="gnome-img" src="<%= asset_path('gnome-button.png') %>" alt="Gnome" />
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="container py-4">
  <div class="row">
    <div class="col-md d-flex justify-content-center align-items-center">
      <div class="text-center py-4">
        <%= cl_image_tag @hat.photo.key, class: "img-fluid"%>
      </div>
    </div>
    <div class="col-md rounded py-4">
      <h3>Edit Booking</h3>
        <%= render "form" %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container py-5">
  <div class="row">
      <div class="col-md-8 col-sm-8 col-12">
        <div class="d-flex p-3">
          <h3>Booking History</h3>
        </div>
        <% @bookings.each do |booking| %>
        <div class="card-booking">
          <%= cl_image_tag booking.hat.photo.key, class: "img-fluid"%>
          <div class="card-booking-infos flex-grow-1">
            <h3><%= booking.hat.style %></h3>
            <p>Booking ID: <%= booking.id %></p>
            <p>Rental Start Date: <%= booking.start_date %></p>
            <p>Rental End Date: <%= booking.end_date %></p>
          </div>
          <%= link_to 'Add a review', new_booking_review_path(booking), remote: true, class: "btn btn-primary review-btn" %>
        </div>
        <% end %>
      </div>
      <div class="col-md-4 col-sm-4 d-none d-sm-block">
        <div class="position-fixed d-flex bottom-0 climbing-gnome">
          <img class="img-fluid" src="<%= asset_path('climbing-gnome.png') %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container py-4">
  <div class="row h-70">
    <div class="col-md">
      <div class="text-center">
        <%= cl_image_tag @hat.photo.key, class: "img-fluid" %>
      </div>
    </div>
    <div class="col-md mt-3">
      <h4>When do you want to rent this hat?</h4>
        <%= render "form" %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container py-5">
  <h1>Booking Confirmation</h1>

  <p>Your booking has been confirmed with the following details:</p>

  <p>Start Date: <%= @booking.start_date %></p>
  <p>End Date: <%= @booking.end_date %></p>

  <p>Thank you for renting a hat!</p>

  <a href="<%= bookings_path %>" class="btn btn-primary">See all of your bookings here</a>
  <a href="<%= edit_hat_booking_path(@booking.hat, @booking) %>" class="btn btn-primary">Edit booking</a>


</div>

app/views/hats/_form.html.erb
<%= simple_form_for @hat do |f| %>
  <%= f.input :style, placeholder: 'Pointy' %>
  <div class="d-flex justify-content-between gap-3">
    <div class="flex-fill">
      <%= f.input :color, placeholder: 'Red' %>
    </div>
    <div class="flex-fill">
      <%= f.input :price, placeholder: '100' %>
    </div>
  </div>
  <%= f.input :description %>
  <%= f.input :photo, as: :file%>
 <div class="d-flex justify-content-between">
    <%= f.submit "Submit Hat", class: "btn btn-primary"%>
    <%= link_to 'Return to all listings', hats_path %>
  </div>

<% end %>

app/views/hats/edit.html.erb
<div class="container py-4">
  <div class="row custom-height">
    <div class="col-md custom-col">
      <img class="img-fluid custom-col" src="<%= asset_path('main-gnome.png') %>">
    </div>
    <div class="col-md">
      <div class="rounded p-3 shadow">
          <h3>Edit your hat</h3>
            <%= render "form" %>
        </div>
    </div>
  </div>
</div>

app/views/hats/index.html.erb
<%# <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= asset_path('banner.jpeg')');"> %>
  <%# <div class="container">
    <h1>Gnome Hats</h1>
    <p>The gnome reveals his <strong>individuality</strong> as much with his hat as with the shape of his nose.</p>
  </div> %>
<%# </div> %>


<div class="container py-5">
  <div class="grid-container">
    <% @hats.each do |hat| %>
      <div class="<%= Hat.random_card_class %>">
        <%= link_to hat_path(hat), class: "text-decoration-none card-product" do %>
          <%= cl_image_tag hat.photo.key%>
          <div class="card-product-info">
            <div>
              <p><%= hat.style %></p>
            </div>
            <p class="card-product-pricing"><%= "£#{hat.price}" %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/hats/new.html.erb
<div class="container py-4">
  <div class="row custom-height">
    <div class="col-md-4 custom-col">
      <img class="img-fluid custom-col" src="<%= asset_path('main-gnome.png') %>">
    </div>
    <div class="col-md-8">
      <div class="rounded p-3 shadow">
          <h3>Add a new hat</h3>
            <%= render "form" %>
        </div>
    </div>
  </div>
</div>

app/views/hats/show.html.erb
<div class="container py-4" style="max-width: 70%;">
  <div class="row">
    <div class="col-md-6">
      <% if @hat.photo.attached? %>
      <%= cl_image_tag @hat.photo.key, class:"img-fluid rounded" %>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="mt-3">
        <h3><%= @hat.style %></h3>
        <p><strong>Colour:</strong> <%= @hat.color %></p>
        <p><strong>Description:</strong> <%= @hat.description %></p>
      </div>
      <div>
        <p>Price: <%= "£#{@hat.price}" %></p>
      </div>
      <% if current_user != @hat.user %>
        <%= link_to "Rent this hat", new_hat_booking_path(@hat), class:"btn btn-primary" %>
      <% else %>
        <div>
          <%= link_to "Edit this hat", edit_hat_path(@hat), class:"btn btn-primary" %>
          <%= link_to "Delete this hat", hat_path(@hat), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
        </div>
      <% end %>
      <div class="mt-4">
        </div>
      </div>
    </div>
  </div>

<%# Link the new reviews to the below once finished %>
  <div id="reviewCarousel" class="carousel slide text-center carousel-dark py-5" data-mdb-ride="carousel">
    <div class="carousel-inner">
      <% reviews = [@hat.reviews]
  #   {
  #     quote: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus et deleniti nesciunt sint eligendi reprehenderit reiciendis, quibusdam illo, beatae quia fugit consequatur laudantium velit magnam error. Consectetur distinctio fugit doloremque."
  #   },
  #   {
  #     quote: "Minus et deleniti nesciunt sint eligendi reprehenderit reiciendis."
  #   },
  #   {
  #     quote: "Reprehenderit reiciendis, quibusdam illo, beatae quia fugit consequatur laudantium velit magnam error. Consectetur distinctio fugit doloremque."
  #   }
  # ] %>
  <h2>Reviews:</h2>
  <% if @hat.reviews.any? %>
      <% @hat.reviews.each_with_index do |testimonial, index| %>
        <div class="carousel-item <%= index == 0 ? 'active' : '' %>" >
          <div class="row d-flex justify-content-center">
            <div class="col-8">
              <p class="text-muted">
                <i class="fas fa-quote-left pe-2"></i>
                <%= testimonial[:comment] %>
              </p>
            </div>
          </div>
          <ul class="list-unstyled d-flex justify-content-center text-warning mb-0">
            <% 5.times do |star_index| %>
              <li><i class="fas <%= star_index < 4 ? 'fa-star' : 'far fa-star' %> fa-sm"></i></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#reviewCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#reviewCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
    <% else %>
    <p>No reviews yet.</p>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gnats :: Gnome Hats</title>
    <link rel="icon" type="image/x-icon" href="images/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homebg">
  <div class="container py-5">
    <h1>Gnome Hats</h1>
    <p>The gnome without his <strong>hat</strong> is not a gnome and he knows it.</p>
    <%# <p>The gnome reveals his <strong>individuality</strong> as much with his hat as with the shape of his nose.</p> %>
    <%# <div class="position-fixed bottom-0"> %>
    <div class="vstack gap-2">
        <%= link_to "Get your gnome on", "hats", class: "btn btn-flat homebtn"%>
        <%= link_to "Sprout a New Hat Listing", "hats/new", class: "btn btn-flat homebtn" %>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@hat, @booking, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/new.html.erb
<div class="container py-4">
  <div class="row custom-height">
    <div class="col-md custom-col">
      <img class="img-fluid custom-col" src="<%= asset_path('main-gnome.png') %>">
    </div>
    <div class="col-md">
      <div class="rounded p-3 shadow">
          <h3>Add a review</h3>
            <%= render "form", class: "btn btn-primary" %>
            <a href="<%= bookings_path %>">See all of your bookings here</a>
        </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-gnats p-0 ">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "main-logo.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All listings", hats_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add hat", new_hat_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My listings", hats_path(user_id: current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <p class="dropdown-item text-muted small"><%= current_user.email %></p>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>